name: Pull and Push Docker Image

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull ghcr.io/immich-app/immich-server:v1.133.1

    - name: Tag Docker image
      run: docker tag ghcr.io/immich-app/immich-server:v1.133.1 kevin517/immich-server:v1.133.1

    - name: Push Docker image
      run: docker push kevin517/immich-server:v1.133.1


